#ifndef __S2_ALPHAPASS_H__
#define __S2_ALPHAPASS_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AlphaPass_ENABLE_BACKDOOR_DIG_INPUT 0
#define __S2_AlphaPass_SET_BACKDOOR_DIG_INPUT 1
#define __S2_AlphaPass_SET_MASTER_1_DIG_INPUT 2
#define __S2_AlphaPass_SET_MASTER_2_DIG_INPUT 3
#define __S2_AlphaPass_SET_MASTER_3_DIG_INPUT 4
#define __S2_AlphaPass_SET_MASTER_4_DIG_INPUT 5
#define __S2_AlphaPass_SET_MASTER_5_DIG_INPUT 6
#define __S2_AlphaPass_INITIALIZE_DIG_INPUT 7
#define __S2_AlphaPass_ENTER_DIG_INPUT 8
#define __S2_AlphaPass_SET_DEFAULT1_DIG_INPUT 9
#define __S2_AlphaPass_SET_DEFAULT2_DIG_INPUT 10
#define __S2_AlphaPass_SET_DEFAULT3_DIG_INPUT 11
#define __S2_AlphaPass_SET_DEFAULT4_DIG_INPUT 12
#define __S2_AlphaPass_SET_DEFAULT5_DIG_INPUT 13
#define __S2_AlphaPass_SET_DEFAULT_BACKDOOR_DIG_INPUT 14


/*
* ANALOG_INPUT
*/

#define __S2_AlphaPass_PASSWORD$_STRING_INPUT 0
#define __S2_AlphaPass_PASSWORD$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __PASSWORD$, __S2_AlphaPass_PASSWORD$_STRING_MAX_LEN );
#define __S2_AlphaPass_DEFAULT1$_STRING_INPUT 1
#define __S2_AlphaPass_DEFAULT1$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __DEFAULT1$, __S2_AlphaPass_DEFAULT1$_STRING_MAX_LEN );
#define __S2_AlphaPass_DEFAULT2$_STRING_INPUT 2
#define __S2_AlphaPass_DEFAULT2$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __DEFAULT2$, __S2_AlphaPass_DEFAULT2$_STRING_MAX_LEN );
#define __S2_AlphaPass_DEFAULT3$_STRING_INPUT 3
#define __S2_AlphaPass_DEFAULT3$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __DEFAULT3$, __S2_AlphaPass_DEFAULT3$_STRING_MAX_LEN );
#define __S2_AlphaPass_DEFAULT4$_STRING_INPUT 4
#define __S2_AlphaPass_DEFAULT4$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __DEFAULT4$, __S2_AlphaPass_DEFAULT4$_STRING_MAX_LEN );
#define __S2_AlphaPass_DEFAULT5$_STRING_INPUT 5
#define __S2_AlphaPass_DEFAULT5$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __DEFAULT5$, __S2_AlphaPass_DEFAULT5$_STRING_MAX_LEN );
#define __S2_AlphaPass_DEFAULT_BACKDOOR$_STRING_INPUT 6
#define __S2_AlphaPass_DEFAULT_BACKDOOR$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __DEFAULT_BACKDOOR$, __S2_AlphaPass_DEFAULT_BACKDOOR$_STRING_MAX_LEN );



/*
* DIGITAL_OUTPUT
*/
#define __S2_AlphaPass_SET_BACKDOOR_FB_DIG_OUTPUT 0
#define __S2_AlphaPass_SET_MASTER_1_FB_DIG_OUTPUT 1
#define __S2_AlphaPass_SET_MASTER_2_FB_DIG_OUTPUT 2
#define __S2_AlphaPass_SET_MASTER_3_FB_DIG_OUTPUT 3
#define __S2_AlphaPass_SET_MASTER_4_FB_DIG_OUTPUT 4
#define __S2_AlphaPass_SET_MASTER_5_FB_DIG_OUTPUT 5


/*
* ANALOG_OUTPUT
*/
#define __S2_AlphaPass_COMPARE_STATUS_ANALOG_OUTPUT 0

#define __S2_AlphaPass_MASTER_OUT$_STRING_OUTPUT 1
#define __S2_AlphaPass_STARS$_STRING_OUTPUT 2


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_AlphaPass_STEMPPASSWORD_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __STEMPPASSWORD, __S2_AlphaPass_STEMPPASSWORD_STRING_MAX_LEN );
#define __S2_AlphaPass_STEMP_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __STEMP, __S2_AlphaPass_STEMP_STRING_MAX_LEN );
#define __S2_AlphaPass_SDEFAULT1$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT1$, __S2_AlphaPass_SDEFAULT1$_STRING_MAX_LEN );
#define __S2_AlphaPass_SDEFAULT2$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT2$, __S2_AlphaPass_SDEFAULT2$_STRING_MAX_LEN );
#define __S2_AlphaPass_SDEFAULT3$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT3$, __S2_AlphaPass_SDEFAULT3$_STRING_MAX_LEN );
#define __S2_AlphaPass_SDEFAULT4$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT4$, __S2_AlphaPass_SDEFAULT4$_STRING_MAX_LEN );
#define __S2_AlphaPass_SDEFAULT5$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT5$, __S2_AlphaPass_SDEFAULT5$_STRING_MAX_LEN );
#define __S2_AlphaPass_SDEFAULTBACKDOOR$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_AlphaPass, __SDEFAULTBACKDOOR$, __S2_AlphaPass_SDEFAULTBACKDOOR$_STRING_MAX_LEN );
#define __S2_AlphaPass_SMASTER$_ARRAY_NUM_ELEMS 6
#define __S2_AlphaPass_SMASTER$_ARRAY_NUM_CHARS 20
CREATE_STRING_ARRAY( S2_AlphaPass, __SMASTER$, __S2_AlphaPass_SMASTER$_ARRAY_NUM_ELEMS, __S2_AlphaPass_SMASTER$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AlphaPass )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_STRUCT( S2_AlphaPass, __PASSWORD$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __DEFAULT1$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __DEFAULT2$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __DEFAULT3$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __DEFAULT4$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __DEFAULT5$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __DEFAULT_BACKDOOR$ );
};

START_NVRAM_VAR_STRUCT( S2_AlphaPass )
{
   DECLARE_STRING_STRUCT( S2_AlphaPass, __STEMPPASSWORD );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __STEMP );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT1$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT2$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT3$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT4$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __SDEFAULT5$ );
   DECLARE_STRING_STRUCT( S2_AlphaPass, __SDEFAULTBACKDOOR$ );
   DECLARE_STRING_ARRAY( S2_AlphaPass, __SMASTER$ );
   unsigned short __ICOMPARESTATUS;
   unsigned short __IMASTER;
   unsigned short __B;
};



#endif //__S2_ALPHAPASS_H__

