#ifndef __S2_NEWOLD_H__
#define __S2_NEWOLD_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_NewOld_RETRIGGER_DIG_INPUT 0


/*
* ANALOG_INPUT
*/


#define __S2_NewOld_CONSOLE_RX$_BUFFER_INPUT 0
#define __S2_NewOld_CONSOLE_RX$_BUFFER_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_NewOld, __CONSOLE_RX$, __S2_NewOld_CONSOLE_RX$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_NewOld_NEWPROGRAM_DIG_OUTPUT 0
#define __S2_NewOld_EXISTINGPROGRAM_DIG_OUTPUT 1
#define __S2_NewOld_DIFFERENTPROGRAM_DIG_OUTPUT 2
#define __S2_NewOld_DIFFERENTCOMPILEDONDATE_DIG_OUTPUT 3


/*
* ANALOG_OUTPUT
*/

#define __S2_NewOld_CONSOLE_TX$_STRING_OUTPUT 0


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_NewOld_SOURCEFILE_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_NewOld, __SOURCEFILE, __S2_NewOld_SOURCEFILE_STRING_MAX_LEN );
#define __S2_NewOld_COMPILEDON_STRING_MAX_LEN 30
CREATE_STRING_STRUCT( S2_NewOld, __COMPILEDON, __S2_NewOld_COMPILEDON_STRING_MAX_LEN );
#define __S2_NewOld_TEMPSOURCEFILE_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_NewOld, __TEMPSOURCEFILE, __S2_NewOld_TEMPSOURCEFILE_STRING_MAX_LEN );
#define __S2_NewOld_TEMPCOMPILEDON_STRING_MAX_LEN 30
CREATE_STRING_STRUCT( S2_NewOld, __TEMPCOMPILEDON, __S2_NewOld_TEMPCOMPILEDON_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_NewOld )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   unsigned short __DONEFLAG;
   DECLARE_STRING_STRUCT( S2_NewOld, __TEMPSOURCEFILE );
   DECLARE_STRING_STRUCT( S2_NewOld, __TEMPCOMPILEDON );
   DECLARE_STRING_STRUCT( S2_NewOld, __CONSOLE_RX$ );
};

START_NVRAM_VAR_STRUCT( S2_NewOld )
{
   DECLARE_STRING_STRUCT( S2_NewOld, __SOURCEFILE );
   DECLARE_STRING_STRUCT( S2_NewOld, __COMPILEDON );
};



#endif //__S2_NEWOLD_H__

